### ISSUE TITLE
Build failures: unknown property 'nexusUsername' & no configured signatory

### ISSUE THREAD

**Issue by juhoautio** [king/bravo#10]
```
gradlew clean build

FAILURE: Build failed with an exception.

* Where:
Build file '~/bravo/build.gradle' line: 93

* What went wrong:
A problem occurred evaluating root project 'bravo'.
> Could not get unknown property 'nexusUsername' for object of type org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer.
```

I know this is trivial to fix locally by removing these lines:
https://github.com/king/bravo/blob/4311dc2ccfe3066c136f9d1bf08d218f2d0c7b43/build.gradle#L92-L98

After that I get:

```
> Task :bravo:signArchives FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bravo:signArchives'.
> Cannot perform signing task ':bravo:signArchives' because it has no configured signatory
```

which can be fixed by removing:

https://github.com/king/bravo/blob/4311dc2ccfe3066c136f9d1bf08d218f2d0c7b43/build.gradle#L54-L56

It would be nice to have some official way to avoid these errors so that there's no need to work on a dirty repo locally. What would you suggest?

**Comment by gyfora** [comment]
Sorry this is a side effect of my last attempt to publish this to the central repo.

I will fix it so it doesn’t affect you after lunch

**Comment by gyfora** [comment]
this should be fixed with the latest commit on master ^^
