### ISSUE TITLE
Support blink 1.5.1

### ISSUE THREAD

**Issue by DG-Wangtao** [king/bravo#18]
Will you support blink 1.5.1 wich use savepoint version3 and is base on flink 1.5.1?
I changed Gradle dependencies form `org.apache.flink` to `com.alibaba.com` and changed flink version to 1.5.1 and some java classes.
 I read state from savepoint successfully but failed while writing state back.
 My changes here : https://github.com/DG-Wangtao/bravo/commit/5cf25896f1a52378baeb48722b3dcd3f13150939

**Comment by gyfora** [comment]
Hi!
The Ververica folks have started some initial work on adding a state connector (similar to bravo) to flink itself. The jira is tracked here:  https://issues.apache.org/jira/browse/FLINK-12047

if you could modify the dependencies to work with blink 1.5.1 to some extent thats good but I dont plan to work on supporting new versions while the work in flink is also on-going

**Comment by gyfora** [comment]
of course if you need help with a specific use-case feel free to reach out to me or write on the flink-ml

**Comment by DG-Wangtao** [comment]
Yeah, thanks.
I just want to use bravo to read some state from my savepoint and it works well. 
Waiting for the Savepoint connector in flink.
