### ISSUE TITLE
Publish artifacts to Maven Central

### ISSUE THREAD

**Issue by mikemintz** [king/bravo#9]
Would it be possible to publish jars for bravo to Maven Central? It would make it much easier to use as a dependency in projects.

**Comment by gyfora** [comment]
I agree, I hope I will have some time today or tomorrow to fix it

**Comment by link3280** [comment]
It would be great if we could install the test jar too, then we could use bravo to write tests about states in Flink Applications.

**Comment by gyfora** [comment]
I think this is done now, you can check the top of the readme, let me know if anything doesnt work, this is the first time I do this ^^
